# Generated by Django 5.2 on 2025-11-10 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_type', models.CharField(max_length=255)),
                ('priority_score', models.PositiveIntegerField(default=0, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'queue_priority',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_counter_queue_node', models.BooleanField(default=False)),
                ('batch_support', models.BooleanField(default=False)),
                ('batch_size', models.PositiveIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.department')),
            ],
            options={
                'db_table': 'queue_department',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Paused', 'Paused')], default='Open', max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='tokens.department')),
            ],
            options={
                'db_table': 'queue_counter',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], default='Open', max_length=255)),
                ('reset', models.BooleanField(default=False)),
                ('reset_type', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Auto', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Canceled', 'Canceled'), ('No Show', 'No Show'), ('In Progress', 'In Progress'), ('Recall', 'Recall')], default='Open', max_length=255)),
                ('token_for', models.CharField(choices=[('D', 'Department'), ('C', 'Counter')], default='D', max_length=1)),
                ('batch_processed', models.BooleanField(default=False)),
                ('token_created_for', models.DateField(default=datetime.date.today, null=True)),
                ('counter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.counter')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.department')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.priority')),
                ('refered_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tokens.tokens')),
            ],
            options={
                'db_table': 'queue_tokens',
            },
        ),
    ]
